"""The narrow OANDA Practice historical-candle and account boundary."""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .reconciliation import (
        OandaPracticeReconciliationReader,
        OandaReconciliationNormalizationError,
    )

from .account import (
    OandaAccountNormalizationError,
    OandaPracticeAccountIdentity,
    OandaPracticeAccountSummarySnapshot,
    OandaPracticeAccountValidator,
    bind_oanda_practice_account,
    is_valid_oanda_practice_account_id,
    read_oanda_practice_account_summary,
)
from .execution import (
    OandaEntryMutationRequester,
    OandaEntryReadbackReader,
    OandaPracticeEntryMutation,
    OandaPracticeEntryMutationNormalizationError,
    OandaPracticeEntryReadbackError,
    OandaPracticeEntryReadbackReader,
    OandaPracticeEntryTranslationError,
    OandaPracticeEntryTranslator,
    OandaPracticeProtectionCompletion,
    OandaPracticeProtectionNormalizationError,
    OandaProtectionMutationRequester,
    OandaProtectionReadbackReader,
    OandaTradeProtectionReader,
    complete_oanda_practice_protection,
    normalize_entry_response,
    normalize_oanda_practice_entry_response,
    resolve_oanda_practice_actual_target,
    translate_entry_order,
    translate_oanda_practice_market_order,
    translate_oanda_practice_take_profit,
    translate_take_profit_order,
)
from .execution_account import (
    OandaPracticeAccountProperties,
    OandaPracticeAccountPropertiesNormalizationError,
    OandaPracticeAccountPropertiesReader,
    OandaPracticeExecutionAccountNormalizationError,
    OandaPracticeExecutionAccountReader,
    OandaPracticeExecutionAccountSnapshot,
    normalize_oanda_practice_execution_account_snapshot,
    read_oanda_practice_account_properties,
    read_oanda_practice_execution_account_snapshot,
)
from .execution_instrument import (
    OandaPracticeExecutionInstrument,
    OandaPracticeExecutionInstrumentNormalizationError,
    OandaPracticeExecutionInstrumentReader,
    read_oanda_practice_execution_instrument,
)
from .exposure_projection import (
    OandaExposureProjectionError,
    project_oanda_practice_eur_usd_exposure_state,
)
from .mutation_request import (
    OandaMutationResponse,
    OandaMutationTransportError,
    OandaPracticeMutationRequester,
    OandaProtectionMutationTransportError,
)
from .orders import (
    OandaPendingOrderNormalizationError,
    OandaPracticePendingOrder,
    OandaPracticePendingOrderInventory,
    OandaPracticePendingOrderReader,
    normalize_oanda_practice_pending_order_inventory,
    read_oanda_practice_pending_order_inventory,
)
from .positions import (
    OandaOpenPositionNormalizationError,
    OandaPracticeOpenPosition,
    OandaPracticeOpenPositionInventory,
    OandaPracticeOpenPositionReader,
    OandaPracticePositionSide,
    normalize_oanda_practice_account_position_inventory,
    normalize_oanda_practice_open_position_inventory,
    read_oanda_practice_open_position_inventory,
)
from .pricing import (
    OandaPracticeEurUsdPricingObservation,
    OandaPracticeEurUsdPricingReader,
    OandaPracticePriceBucket,
    OandaPricingNormalizationError,
    read_oanda_practice_eur_usd_pricing,
)
from .pricing_projection import (
    OandaPracticeExecutablePriceCandidate,
    OandaPracticeExecutablePricingProjection,
    OandaPricingBucketEvidence,
    OandaPricingProjectionError,
    project_oanda_practice_executable_pricing,
)
from .risk_projection import project_oanda_practice_account_state
from .source import (
    OANDA_PRACTICE_BASE_URL,
    FetchDiagnostics,
    FetchResult,
    HistoricalBarSource,
    IncompleteCandle,
    OandaAuthError,
    OandaConfigurationError,
    OandaError,
    OandaHistoricalBarSource,
    OandaHistoricalSource,
    OandaNormalizationError,
    OandaRequestError,
    RequestDiagnostic,
)
from .trades import (
    OandaOpenTradeNormalizationError,
    OandaPracticeOpenTrade,
    OandaPracticeOpenTradeInventory,
    OandaPracticeOpenTradeReader,
    normalize_oanda_practice_open_trade_inventory,
    read_oanda_practice_open_trade_inventory,
)

__all__ = [
    "OandaAccountNormalizationError",
    "OandaPracticeAccountIdentity",
    "OandaPracticeAccountSummarySnapshot",
    "OandaPracticeAccountValidator",
    "OandaPracticeAccountProperties",
    "OandaPracticeAccountPropertiesNormalizationError",
    "OandaPracticeAccountPropertiesReader",
    "OandaPracticeExecutionAccountNormalizationError",
    "OandaPracticeExecutionAccountReader",
    "OandaPracticeExecutionAccountSnapshot",
    "normalize_oanda_practice_execution_account_snapshot",
    "bind_oanda_practice_account",
    "is_valid_oanda_practice_account_id",
    "read_oanda_practice_account_properties",
    "read_oanda_practice_execution_account_snapshot",
    "OandaExposureProjectionError",
    "project_oanda_practice_account_state",
    "project_oanda_practice_eur_usd_exposure_state",
    "read_oanda_practice_account_summary",
    "FetchDiagnostics",
    "FetchResult",
    "HistoricalBarSource",
    "IncompleteCandle",
    "OANDA_PRACTICE_BASE_URL",
    "OandaAuthError",
    "OandaConfigurationError",
    "OandaError",
    "OandaHistoricalBarSource",
    "OandaHistoricalSource",
    "OandaNormalizationError",
    "OandaRequestError",
    "RequestDiagnostic",
    "OandaOpenPositionNormalizationError",
    "OandaPracticeOpenPosition",
    "OandaPracticeOpenPositionInventory",
    "OandaPracticeOpenPositionReader",
    "OandaPracticePositionSide",
    "normalize_oanda_practice_account_position_inventory",
    "read_oanda_practice_open_position_inventory",
    "OandaPricingBucketEvidence",
    "OandaPricingProjectionError",
    "OandaPracticeExecutablePriceCandidate",
    "OandaPracticeExecutablePricingProjection",
    "project_oanda_practice_executable_pricing",
    "OandaPendingOrderNormalizationError",
    "OandaPracticePendingOrder",
    "OandaPracticePendingOrderInventory",
    "OandaPracticePendingOrderReader",
    "read_oanda_practice_pending_order_inventory",
    "OandaPracticeEurUsdPricingObservation",
    "OandaPracticeEurUsdPricingReader",
    "OandaPracticePriceBucket",
    "OandaPricingNormalizationError",
    "read_oanda_practice_eur_usd_pricing",
    "OandaPracticeReconciliationReader",
    "OandaReconciliationNormalizationError",
    "OandaOpenTradeNormalizationError",
    "OandaPracticeOpenTrade",
    "OandaPracticeOpenTradeInventory",
    "OandaPracticeOpenTradeReader",
    "normalize_oanda_practice_open_trade_inventory",
    "read_oanda_practice_open_trade_inventory",
    "normalize_oanda_practice_open_position_inventory",
    "normalize_oanda_practice_pending_order_inventory",
    "OandaPracticeExecutionInstrument",
    "OandaPracticeExecutionInstrumentNormalizationError",
    "OandaPracticeExecutionInstrumentReader",
    "read_oanda_practice_execution_instrument",
    "OandaPracticeEntryTranslationError",
    "OandaPracticeEntryTranslator",
    "OandaEntryMutationRequester",
    "OandaEntryReadbackReader",
    "OandaProtectionMutationRequester",
    "OandaProtectionReadbackReader",
    "OandaTradeProtectionReader",
    "OandaPracticeProtectionCompletion",
    "OandaPracticeProtectionNormalizationError",
    "complete_oanda_practice_protection",
    "resolve_oanda_practice_actual_target",
    "translate_oanda_practice_take_profit",
    "translate_take_profit_order",
    "OandaMutationResponse",
    "OandaMutationTransportError",
    "OandaProtectionMutationTransportError",
    "OandaPracticeEntryMutation",
    "OandaPracticeEntryMutationNormalizationError",
    "OandaPracticeEntryReadbackError",
    "OandaPracticeEntryReadbackReader",
    "OandaPracticeMutationRequester",
    "normalize_entry_response",
    "normalize_oanda_practice_entry_response",
    "translate_entry_order",
    "translate_oanda_practice_market_order",
]


def __getattr__(name: str) -> object:
    if name in {
        "OandaPracticeReconciliationReader",
        "OandaReconciliationNormalizationError",
    }:
        from . import reconciliation

        return getattr(reconciliation, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
