/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Live */
    get: operations['live_health_live_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations['ready_health_ready_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/strategies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listing */
    get: operations['listing_api_v1_strategies_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/strategies/{strategy_key}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detail */
    get: operations['detail_api_v1_strategies__strategy_key__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/historical-data/capability': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Capability */
    get: operations['capability_api_v1_historical_data_capability_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/historical-data/load-requests/active': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Active */
    get: operations['active_api_v1_historical_data_load_requests_active_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/historical-data/load-requests': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create */
    post: operations['create_api_v1_historical_data_load_requests_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/historical-data/load-requests/{request_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get */
    get: operations['get_api_v1_historical_data_load_requests__request_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/experiments/configuration-options': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Options */
    get: operations['options_api_v1_experiments_configuration_options_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/experiments/coverage-validations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Coverage */
    post: operations['coverage_api_v1_experiments_coverage_validations_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/experiments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listing */
    get: operations['listing_api_v1_experiments_get'];
    put?: never;
    /** Create */
    post: operations['create_api_v1_experiments_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/experiments/comparison': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Compare */
    get: operations['compare_api_v1_experiments_comparison_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/experiments/{experiment_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detail */
    get: operations['detail_api_v1_experiments__experiment_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/experiments/{experiment_id}/run': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run */
    post: operations['run_api_v1_experiments__experiment_id__run_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/experiments/{experiment_id}/equity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Equity */
    get: operations['equity_api_v1_experiments__experiment_id__equity_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/experiments/{experiment_id}/price-analysis': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Price Analysis */
    get: operations['price_analysis_api_v1_experiments__experiment_id__price_analysis_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/experiments/{experiment_id}/trades': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Trades */
    get: operations['trades_api_v1_experiments__experiment_id__trades_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/experiments/{experiment_id}/trades/{sequence_number}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Trade */
    get: operations['trade_api_v1_experiments__experiment_id__trades__sequence_number__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ComparisonDifferenceResponse */
    ComparisonDifferenceResponse: {
      /** Path */
      path: string;
      /** Values */
      values: {
        [key: string]: unknown;
      };
    };
    /** ComparisonExperimentResponse */
    ComparisonExperimentResponse: {
      /** Slot */
      slot: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Label */
      label: string;
      /** Strategy */
      strategy: {
        [key: string]: unknown;
      };
      /** Instrument */
      instrument: {
        [key: string]: unknown;
      };
      /** Datasetsnapshot */
      datasetSnapshot: {
        [key: string]: unknown;
      };
      /** Tradingperiod */
      tradingPeriod: {
        [key: string]: unknown;
      };
      /** Parameters */
      parameters: {
        [key: string]: unknown;
      };
      /** Startingcapital */
      startingCapital: {
        [key: string]: unknown;
      };
      /** Risk */
      risk: {
        [key: string]: unknown;
      };
      /** Simulation */
      simulation: {
        [key: string]: unknown;
      };
      /** Modelversion */
      modelVersion: string;
      /** Metriccontract */
      metricContract: {
        [key: string]: unknown;
      };
      /** Metrics */
      metrics: {
        [key: string]: unknown;
      };
    };
    /** ComparisonWarningResponse */
    ComparisonWarningResponse: {
      /** Code */
      code: string;
      /** Severity */
      severity: string;
      /** Explanation */
      explanation: string;
      /** Paths */
      paths: string[];
    };
    /** ExperimentComparisonResponse */
    ExperimentComparisonResponse: {
      /** Experiments */
      experiments: components['schemas']['ComparisonExperimentResponse'][];
      /** Differences */
      differences: components['schemas']['ComparisonDifferenceResponse'][];
      /** Warnings */
      warnings: components['schemas']['ComparisonWarningResponse'][];
      /** Changedparameterkeys */
      changedParameterKeys: string[];
      /** Strongparameterisolation */
      strongParameterIsolation: boolean;
    };
    /** ExperimentConfigurationOptionsResponse */
    ExperimentConfigurationOptionsResponse: {
      /** Strategyversions */
      strategyVersions: components['schemas']['ExperimentStrategyVersionOptionResponse'][];
      /** Datasetsnapshots */
      datasetSnapshots: components['schemas']['ExperimentDatasetSnapshotOptionResponse'][];
      /** Defaults */
      defaults: {
        [key: string]: unknown;
      };
      /** Simulationassumptions */
      simulationAssumptions: {
        [key: string]: unknown;
      };
    };
    /** ExperimentCreateRequest */
    ExperimentCreateRequest: {
      /**
       * Strategyversionid
       * Format: uuid
       */
      strategyVersionId: string;
      /**
       * Datasetsnapshotid
       * Format: uuid
       */
      datasetSnapshotId: string;
      /**
       * Tradingstart
       * Format: date-time
       */
      tradingStart: string;
      /**
       * Tradingend
       * Format: date-time
       */
      tradingEnd: string;
      /** Startingcapital */
      startingCapital: number | string;
      /** Riskpertrade */
      riskPerTrade: number | string;
      /** Parameters */
      parameters: {
        [key: string]: unknown;
      };
      /** Slippageticks */
      slippageTicks: number;
      /** Commissionperunit */
      commissionPerUnit: number | string;
    };
    /** ExperimentDatasetSnapshotOptionResponse */
    ExperimentDatasetSnapshotOptionResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Fingerprint */
      fingerprint: string;
      /** Coveragestart */
      coverageStart: string;
      /** Coverageend */
      coverageEnd: string;
      /** Snapshotschema */
      snapshotSchema: string;
      /** Integrity */
      integrity: {
        [key: string]: unknown;
      };
    };
    /** ExperimentStrategyVersionOptionResponse */
    ExperimentStrategyVersionOptionResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Strategykey */
      strategyKey: string;
      /** Name */
      name: string;
      /** Version */
      version: number;
      /** Displayname */
      displayName: string;
      /** Createdat */
      createdAt: string;
      /** Implementationkey */
      implementationKey: string;
      /** Sourcefingerprint */
      sourceFingerprint: string;
      /** Parameterschema */
      parameterSchema: {
        [key: string]: unknown;
      }[];
      /** Required historical context bars */
      requiredHistoricalContextBars: number;
      /** Architecture */
      architecture: string;
      /** Executionavailable */
      executionAvailable: boolean;
      /** Unavailablereason */
      unavailableReason: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string;
      /** Service */
      service: string;
      /** Checks */
      checks: {
        [key: string]: string;
      };
    };
    /** HistoricalDataCapabilityResponse */
    HistoricalDataCapabilityResponse: {
      /** Provider */
      provider: string;
      /** Instrument */
      instrument: string;
      /** Resolution */
      resolution: string;
      /** Components */
      components: string[];
      /** Available */
      available: boolean;
      /** Reasoncode */
      reasonCode: string | null;
    };
    /** HistoricalDataLoadRequest */
    HistoricalDataLoadRequest: {
      /**
       * Strategyversionid
       * Format: uuid
       */
      strategyVersionId: string;
      /**
       * Tradingstart
       * Format: date-time
       */
      tradingStart: string;
      /**
       * Tradingend
       * Format: date-time
       */
      tradingEnd: string;
    };
    /** HistoricalDataLoadStatusResponse */
    HistoricalDataLoadStatusResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Displaylabel */
      displayLabel: string;
      /** Status */
      status: string;
      /** Statusurl */
      statusUrl: string;
      /** Source */
      source: {
        [key: string]: unknown;
      };
      /** Requestedperiod */
      requestedPeriod: {
        [key: string]: string;
      };
      /** Loadrange */
      loadRange: {
        [key: string]: string;
      };
      /** Progress */
      progress: {
        [key: string]: unknown;
      };
      /** Coverage */
      coverage: {
        [key: string]: unknown;
      } | null;
      /** Snapshot */
      snapshot: {
        [key: string]: unknown;
      } | null;
      /** Experimentvalidation */
      experimentValidation: {
        [key: string]: unknown;
      } | null;
      /** Failure */
      failure: {
        [key: string]: unknown;
      } | null;
      /** Createdat */
      createdAt: string;
      /** Startedat */
      startedAt: string | null;
      /** Finishedat */
      finishedAt: string | null;
    };
    /** PeriodRequest */
    PeriodRequest: {
      /**
       * Strategyversionid
       * Format: uuid
       */
      strategyVersionId: string;
      /**
       * Datasetsnapshotid
       * Format: uuid
       */
      datasetSnapshotId: string;
      /**
       * Tradingstart
       * Format: date-time
       */
      tradingStart: string;
      /**
       * Tradingend
       * Format: date-time
       */
      tradingEnd: string;
    };
    PriceAnalysisBarResponse: {
      t: string;
      o: string;
      h: string;
      l: string;
      c: string;
    };
    PriceAnalysisDiagnosticsResponse: {
      truncated: boolean;
      emaPeriod: number;
      requiredHistoricalContextBars: number;
      snapshotFingerprint: string;
      m15EligibleCount: number;
      m15ReturnedCount: number;
      tradeEligibleCount: number;
      tradeReturnedCount: number;
      omittedRange: { [key: string]: string } | null;
      omittedM15Count: number;
      omittedTradeCount: number;
    };
    PriceAnalysisEmaResponse: { t: string; v: string };
    PriceAnalysisFactResponse: {
      tradeSequence: number;
      reference: { [key: string]: string };
      sweep: { [key: string]: string };
      confirmation: { [key: string]: string };
    };
    PriceAnalysisPointResponse: { t: string; price: string };
    PriceAnalysisRangeResponse: { price: string; from: string; to: string };
    PriceAnalysisResponse: {
      m15: components['schemas']['PriceAnalysisBarResponse'][];
      ema: components['schemas']['PriceAnalysisEmaResponse'][];
      tradingWindow: components['schemas']['PriceAnalysisWindowResponse'];
      trades: components['schemas']['PriceAnalysisTradeResponse'][];
      reference: components['schemas']['PriceAnalysisFactResponse'][];
      diagnostics: components['schemas']['PriceAnalysisDiagnosticsResponse'];
      provenance?: { [key: string]: unknown };
      gaps?: { [key: string]: unknown }[];
      evidence?: components['schemas']['PriceAnalysisEvidenceResponse'][];
      landmarks?: components['schemas']['PriceAnalysisLandmarkResponse'][];
      proposalDiagnostics?: components['schemas']['ProposalStatusResponse'][];
      setupFacts?: { [key: string]: unknown }[];
    };
    PriceAnalysisEvidenceResponse: {
      tradeSequence: number;
      setup: { [key: string]: unknown };
    };
    PriceAnalysisLandmarkResponse: {
      kind: string;
      tradeSequence: number;
      time: string;
      high?: string | null;
      low?: string | null;
      price?: string | null;
      basis?: string | null;
    };
    ProposalStatusResponse: {
      tradeSequence: number;
      entryPolicy?: string | null;
      triggerPrice?: string | null;
      triggerPriceBasis?: string | null;
      expiry?: string | null;
      expiryBars?: number | null;
      proposalStatus: string;
      diagnostics: { [key: string]: unknown };
    };
    PriceAnalysisTradeResponse: {
      sequence: number;
      direction: string;
      entry: components['schemas']['PriceAnalysisPointResponse'];
      exit: components['schemas']['PriceAnalysisPointResponse'] | null;
      stop: components['schemas']['PriceAnalysisRangeResponse'] | null;
      target: components['schemas']['PriceAnalysisRangeResponse'] | null;
    };
    PriceAnalysisWindowResponse: { start: string; end: string };
    /** StrategyCatalogItemResponse */
    StrategyCatalogItemResponse: {
      /** Strategykey */
      strategyKey: string;
      /** Name */
      name: string;
      /** Description */
      description: string;
      latestVersion:
        components['schemas']['StrategyLatestVersionResponse'] | null;
      /** Versioncount */
      versionCount: number;
      /** Experimentcount */
      experimentCount: number;
      /** Lastexperimentat */
      lastExperimentAt: string | null;
    };
    /** StrategyCatalogResponse */
    StrategyCatalogResponse: {
      /** Items */
      items: components['schemas']['StrategyCatalogItemResponse'][];
    };
    /** StrategyDetailResponse */
    StrategyDetailResponse: {
      /** Strategykey */
      strategyKey: string;
      /** Name */
      name: string;
      /** Description */
      description: string;
      /** Versioncount */
      versionCount: number;
      /** Experimentcount */
      experimentCount: number;
      /** Lastexperimentat */
      lastExperimentAt: string | null;
      /** Versions */
      versions: components['schemas']['StrategyVersionHistoryResponse'][];
    };
    /** StrategyLatestVersionResponse */
    StrategyLatestVersionResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Versionnumber */
      versionNumber: number;
      /** Displayname */
      displayName: string;
    };
    /** StrategySourceManifestItem */
    StrategySourceManifestItem: {
      /** Relativepath */
      relativePath: string;
      /** Bytelength */
      byteLength: number;
    };
    /** StrategyVersionHistoryResponse */
    StrategyVersionHistoryResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Displayname */
      displayName: string;
      /** Versionnumber */
      versionNumber: number;
      /** Implementationkey */
      implementationKey: string;
      /** Sourcefingerprint */
      sourceFingerprint: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Gitsha */
      gitSha: string | null;
      /** Sourcemanifest */
      sourceManifest: components['schemas']['StrategySourceManifestItem'][];
      /** Parameterschema */
      parameterSchema: {
        [key: string]: unknown;
      }[];
      /** Contexttimeframes */
      contextTimeframes: string[];
      /** Timeframe */
      timeframe: string;
      /** Required historical context bars */
      requiredHistoricalContextBars: number;
      /** Stateschemaversion */
      stateSchemaVersion: number;
      /** Capabilities */
      capabilities: string[];
      /** Experimentcount */
      experimentCount: number;
      /** Lastusedat */
      lastUsedAt: string | null;
      /** Executionavailable */
      executionAvailable: boolean;
      /** Unavailablereason */
      unavailableReason: string | null;
      /** Market requirements */
      marketRequirements: {
        [key: string]: unknown;
      };
      /** Trader-readable methodology */
      methodology: {
        [key: string]: unknown;
      };
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  price_analysis_api_v1_experiments__experiment_id__price_analysis_get: {
    parameters: {
      query?: never;
      header?: never;
      path: { experiment_id: string };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          'application/json': components['schemas']['PriceAnalysisResponse'];
        };
      };
      422: {
        headers: { [name: string]: unknown };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  live_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  ready_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  listing_api_v1_strategies_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StrategyCatalogResponse'];
        };
      };
    };
  };
  detail_api_v1_strategies__strategy_key__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        strategy_key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StrategyDetailResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  capability_api_v1_historical_data_capability_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HistoricalDataCapabilityResponse'];
        };
      };
    };
  };
  active_api_v1_historical_data_load_requests_active_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HistoricalDataLoadStatusResponse'];
        };
      };
    };
  };
  create_api_v1_historical_data_load_requests_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['HistoricalDataLoadRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HistoricalDataLoadStatusResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_api_v1_historical_data_load_requests__request_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        request_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HistoricalDataLoadStatusResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  options_api_v1_experiments_configuration_options_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExperimentConfigurationOptionsResponse'];
        };
      };
    };
  };
  coverage_api_v1_experiments_coverage_validations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PeriodRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  listing_api_v1_experiments_get: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_api_v1_experiments_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ExperimentCreateRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  compare_api_v1_experiments_comparison_get: {
    parameters: {
      query: {
        experimentId: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExperimentComparisonResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  detail_api_v1_experiments__experiment_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        experiment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  run_api_v1_experiments__experiment_id__run_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        experiment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  equity_api_v1_experiments__experiment_id__equity_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        experiment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  trades_api_v1_experiments__experiment_id__trades_get: {
    parameters: {
      query?: {
        limit?: number;
        afterSequence?: number;
      };
      header?: never;
      path: {
        experiment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  trade_api_v1_experiments__experiment_id__trades__sequence_number__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        experiment_id: string;
        sequence_number: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
