"""Read-only PAPER application seams."""

from .current_analytical_frontier import (
    AnalyticalFrontierDataError,
    AnalyticalFrontierError,
    CurrentAnalyticalFrontier,
    NoCurrentAnalyticalFrontierError,
    load_current_analytical_frontier,
)
from .execution import (
    BrokerFillFacts,
    BrokerProtectionOrder,
    BrokerRejection,
    BrokerUncertainty,
    ExecutionAccountIdentity,
    ExecutionCorrelation,
    ExecutionObservationProvenance,
    PaperExecutionContractError,
    PaperExecutionError,
    PaperExecutionInstruction,
    PaperExecutionOutcome,
    PaperExecutionRefusal,
    PaperExecutionRefusalCode,
    PaperExecutionResult,
    ProtectionConfirmation,
    ProtectionLegStatus,
    TransactionProvenance,
    correlation_for_attempt,
)
from .execution_application import (
    PaperEntryMutation,
    PaperExecutionApplication,
    PaperExecutionReader,
    PaperPricingReader,
    PaperProtectionCompletion,
    PricingReaderFactory,
    execute_paper_execution,
)
from .risk_evaluation import (
    PaperCandidateRiskEvaluation,
    PaperObservationProvenance,
    PaperPricingEvidence,
    PaperRiskEvaluation,
    PaperRiskEvaluationError,
    PaperRiskOutcome,
    evaluate_paper_risk,
)
from .strategy_evaluation import (
    PaperStrategyEvaluationError,
    evaluate_current_paper_strategy,
)

__all__ = [
    "AnalyticalFrontierDataError",
    "AnalyticalFrontierError",
    "CurrentAnalyticalFrontier",
    "NoCurrentAnalyticalFrontierError",
    "PaperEntryMutation",
    "PaperExecutionApplication",
    "PaperExecutionReader",
    "PaperPricingReader",
    "PaperProtectionCompletion",
    "PricingReaderFactory",
    "BrokerFillFacts",
    "BrokerProtectionOrder",
    "BrokerRejection",
    "BrokerUncertainty",
    "ExecutionAccountIdentity",
    "ExecutionCorrelation",
    "ExecutionObservationProvenance",
    "PaperExecutionContractError",
    "PaperExecutionError",
    "PaperExecutionInstruction",
    "PaperExecutionOutcome",
    "PaperExecutionRefusal",
    "PaperExecutionRefusalCode",
    "PaperExecutionResult",
    "PaperCandidateRiskEvaluation",
    "PaperObservationProvenance",
    "PaperPricingEvidence",
    "PaperRiskEvaluation",
    "PaperRiskEvaluationError",
    "PaperRiskOutcome",
    "PaperStrategyEvaluationError",
    "ProtectionConfirmation",
    "ProtectionLegStatus",
    "TransactionProvenance",
    "correlation_for_attempt",
    "evaluate_current_paper_strategy",
    "execute_paper_execution",
    "evaluate_paper_risk",
    "load_current_analytical_frontier",
]
